apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: spring-cloud-config-server
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: spring-cloud-config-server
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  - name: labels
    value:
      anetworking.knative.dev/visibility: cluster-local
  source:
    git:
      url: https://github.com/gm2552/spring-cloud-config-server.git
      ref:
        branch: main
